# This is a basic workflow to help you get started with Actions

name: Trigger AppVeyor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 0 1 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: run_webhook
        with:
          route: POST https://ci.appveyor.com/api/builds
          headers: 'Authorization: Bearer :app_veyor'
          accountName: guibranco
          projectSlug: cepaberto
          branch: master
          app_veyor: ${{secrets.APP_VEYOR}} 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: "echo latest release: ${{ steps.run_webhook.outputs.data }}"  
