# This is a basic workflow to help you get started with Actions

name: Trigger AppVeyor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 1 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  triggerNewBuild:
    steps:
      - uses: fjogeleit/http-request-action@master
        id: call_app_veyor
        with:
            url: 'https://ci.appveyor.com/api/builds'
            method: 'POST'
            bearerToken: ${{ secrets.app_veyor }}
            data: "{'accountName':'guibranco','projectSlug':'cepaberto','branch':'master'}"
      - run: "${{ steps.call_app_veyor.response }}"  
