name: Trigger AppVeyor
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 1 * *"
jobs:
  triggerNewBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        id: call_app_veyor
        with:
            url: 'https://ci.appveyor.com/api/builds'
            method: 'POST'
            bearerToken: ${{ secrets.app_veyor }}
            data: '{"accountName":"guibranco","projectSlug":"cepaberto","branch":"master"}'
      - run: "${{ steps.call_app_veyor.response }}"  
